# Python In-class Exercise

### 1. Write a program to check whether an year entered by an user is leap year or not

In [3]:
year = int(input('Enter a year:\t'))

def isLeapYear(year: int) -> bool:
    if not year % 4:
        if not year % 100:
            return not year % 400
        else:
            return True
    
    return False

print(f'{year} is {"a" if isLeapYear(year) else "not a"} leap year!')

2004 is a leap year!


### 2. Take a string containing punctuation marks as an input from user and write a program to remove all the  punctuation marks from a string

In [7]:
punctuations = ['!', '.', '?', ',', ':', ';', '-', '(', ')', '\'', '\"', '...']

string = input('Enter a sentence:\t')

string = ''.join(list(filter(lambda x: x not in punctuations, string)))
print(f'String without punctuation marks :\t{string}')

String without punctuation marks :	I am the best he said


### 3. Take two separate numbers as input from the user and Write a program to swap 2 numbers without using temporary variable

In [8]:
a, b = map(int, input().split())

def swap(a, b):
    # using xor method
    a ^= b
    b ^= a
    a ^= b
    return a, b

print(f'Before swapping => a = {a}, b = {b}\nAfter swapping =>', end="")
a, b = swap(a, b)
print(f'a = {a}, b = {b}')

Before swapping => a = 10, b = 20
After swapping =>a = 20, b = 10


### 4. Write a program to print product of following variables
<br> integer = 10 
<br> string = "15"

### 5. Write a program to print following pattern
<br>a
<br>b c
<br>d e f
<br>g h i j
<br>k l m n o
<br>p q r s t u

In [34]:
# The input here is, the number of alphabets the user wants in the pattern
# (to make it dynamic)

limit = int(input('Enter a number in the range [1, 26] =>'))

if limit not in range(1, 27):
    print(f'Invalid input! Choice out of range ({limit})')
else:
    i = 1
    line = 1
    while i <= limit:
        j = 1
        while j <= line:
            if i > 26 or i > limit:
                break
            print(chr(96 + i), end=" ")
            j += 1
            i += 1
        line += 1
        print()

a 
b c 
d e f 
g h i j 
k l m n o 
p q r s t u 
v w x y z 


### 6. Write a program to print tables from 2 to n, where n is provided by user

In [1]:
n = int(input('Enter the limit:\t'))

for i in range(2, n + 1):
    for j in range(1, 11):
        print(f'{i} * {j} = {i * j} ')
    print('=' * 15)

2 * 1 = 2 
2 * 2 = 4 
2 * 3 = 6 
2 * 4 = 8 
2 * 5 = 10 
2 * 6 = 12 
2 * 7 = 14 
2 * 8 = 16 
2 * 9 = 18 
2 * 10 = 20 
3 * 1 = 3 
3 * 2 = 6 
3 * 3 = 9 
3 * 4 = 12 
3 * 5 = 15 
3 * 6 = 18 
3 * 7 = 21 
3 * 8 = 24 
3 * 9 = 27 
3 * 10 = 30 
4 * 1 = 4 
4 * 2 = 8 
4 * 3 = 12 
4 * 4 = 16 
4 * 5 = 20 
4 * 6 = 24 
4 * 7 = 28 
4 * 8 = 32 
4 * 9 = 36 
4 * 10 = 40 
5 * 1 = 5 
5 * 2 = 10 
5 * 3 = 15 
5 * 4 = 20 
5 * 5 = 25 
5 * 6 = 30 
5 * 7 = 35 
5 * 8 = 40 
5 * 9 = 45 
5 * 10 = 50 
6 * 1 = 6 
6 * 2 = 12 
6 * 3 = 18 
6 * 4 = 24 
6 * 5 = 30 
6 * 6 = 36 
6 * 7 = 42 
6 * 8 = 48 
6 * 9 = 54 
6 * 10 = 60 
7 * 1 = 7 
7 * 2 = 14 
7 * 3 = 21 
7 * 4 = 28 
7 * 5 = 35 
7 * 6 = 42 
7 * 7 = 49 
7 * 8 = 56 
7 * 9 = 63 
7 * 10 = 70 
8 * 1 = 8 
8 * 2 = 16 
8 * 3 = 24 
8 * 4 = 32 
8 * 5 = 40 
8 * 6 = 48 
8 * 7 = 56 
8 * 8 = 64 
8 * 9 = 72 
8 * 10 = 80 
9 * 1 = 9 
9 * 2 = 18 
9 * 3 = 27 
9 * 4 = 36 
9 * 5 = 45 
9 * 6 = 54 
9 * 7 = 63 
9 * 8 = 72 
9 * 9 = 81 
9 * 10 = 90 
10 * 1 = 10 
10 * 2 = 20 
10 * 3 = 30 
10 * 4 

### 7. Write a program to read height (in centimeters) from user and then convert it to feet and inches

In [30]:
cm = int(input('Enter height in centimeters:\t'))

feet, inch = cm * 0.0328084, cm * 0.393701
print(f'{cm} cm is {feet} feet and {inch} inch')

1 cm is 0.0328084 feet and 0.393701 inch


### 8. Write a program to print following pattern

                                                *
                                                * * 
                                                * * *
                                                * *
                                                *

In [29]:
n = int(input('Enter the limit:\t'))

# upper half
i = 1
while i <= n:
    j = 1
    while j <= i:
        j += 1
        print('*', end=" ")
    print()
    i += 1

# lower half
i = n - 1
while i >= 0:
    j = 1
    while j <= i:
        j += 1
        print('*', end=" ")
    print()
    i -= 1


* 
* * 
* * * 
* * * * 
* * * 
* * 
* 



### 9. Below list contains age and name of five students. Convert the list into a dictionary such that the name is taken as key and the age before their name is taken as thier respective value in the dictionary

students = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton']
Output: {'Jon':26, 'Roger':34, 'Jessica':13, 'Monica':24, 'Ashton':65}

In [37]:
students = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton']
names, ages = [], []

for i, val in enumerate(students):
    if i % 2 == 1:
        names.append(val)
    else:
        ages.append(val)


result = dict(zip(names, ages))
print(result)

{'Jon': 26, 'Roger': 34, 'Jessica': 13, 'Monica': 24, 'Ashton': 65}


### 10. Write a program to check whether two strings, taken from user, are anagram or not

In [39]:
string1, string2 = input('Enter first String:\t').lower(), input('Enter second string:\t').lower()

def calculateFrequency(string: str) -> dict:
    f = {}
    for s in string:
        f[s] = f.get(s, 0) + 1
    
    return f


def isAnagram(string1: str, string2: str) -> bool:
    freq1, freq2 = calculateFrequency(string1), calculateFrequency(string2)

    for k, v in freq1.items():
        if freq2.get(k, 0) != v:
            return False
    return True

print(isAnagram(string1, string2))

True


### 11. Write a program that sorts all the elements of the list according to the first letter, irrespective of their cases (uppercase or lowercase). Note: Do not use any inbuilt sorting function

In [94]:
names = ['Sridhar', 'Davis', 'Ajay', 'deepak', 'silpa']

sorted(names, key=lambda x: x[0].lower())

['Ajay', 'Davis', 'deepak', 'Sridhar', 'silpa']

### 12. Write a program that prints a list of sour fruits from the below tuple:
<br>fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','soUr'), ('Kiwi','Sour'), ('Apples','sweet'), ('Orange','sour'), ('Blueberries','sweet'), ('Limes','Sour') ) 

<br>**Output**: Sour Fruits: ['Lemon', 'Grapes', 'Kiwi', 'Orange', 'Limes']

In [44]:
fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','soUr'), ('Kiwi','Sour'), ('Apples','sweet'), ('Orange','sour'), ('Blueberries','sweet'), ('Limes','Sour') )

sourFruits = tuple(filter(lambda x: x[1].lower() == 'sour', fruits))
result = [x for x, y in sourFruits]
print(f'Sour Fruits: {", ".join(result)}')

Sour Fruits: Lemon, Grapes, Kiwi, Orange, Limes


### 13. Given below are the list of positive and negative words. Also a list of tweets is provided. Separate out the positive and negative comments

<br>positive = ['good','awesome', 'best', 'nice']

<br>negative = ['worst','awful', 'bad']

<br>tweets = ['This government policies are good', 
'bad implementation', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'The wine tastes awful', 'It's nice to hear this little kid's laugh']

In [46]:
positive = ['good','awesome', 'best', 'nice']
negative = ['worst','awful', 'bad']


tweets = ['This government policies are good', 'bad implementation', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'The wine tastes awful', 'It\'s nice to hear this little kid\'s laugh']

positiveComments, negativeComments = [], []

for tweet in tweets:
    for word in tweet.split():
        if word.lower() in positive:
            positiveComments.append(tweet)
            break
        if word.lower() in negative:
            negativeComments.append(tweet)
            break

print('Positive Comments:\t', positiveComments)
print('Negative Comments:\t', negativeComments)

Positive Comments:	 ['This government policies are good', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', "It's nice to hear this little kid's laugh"]
Negative Comments:	 ['bad implementation', 'The wine tastes awful']


### 14. Write a program that performs multiplication of the following two matrix

In [48]:
import numpy as np

r1, c1 = map(int, input('Enter row and column of first matrix:\t').split())
r2, c2 = map(int, input('Enter row and column of second matrix:\t').split())

if r2 != c1:
    print('Matrix Multiplication not possible')
else:
    print('Enter matrix A =>')
    
    A = np.array(
        [np.array(list(map(int, input(f'Enter row {_} =>').split()))) for _ in range(r1)]
    )

    print('Enter matrix B =>')
    B = np.array(
        [np.array(list(map(int, input(f'Enter row {_} =>').split()))) for _ in range(r2)]
    )

    print(f'Matrix Multiplication of {A} and {B} is => {np.matmul(A, B)}')

Enter matrix A =>
Enter matrix B =>
Matrix Multiplication of [[1 1]
 [1 1]] and [[1 1]
 [1 1]] is => [[2 2]
 [2 2]]


### 15. Write a program to remove space from keys of the given dictionary

Employee = {'emp 01' : 'Raj', 'emp 02' : 'Sheela', 'emp 0 3 ': 'Joseph'}; 

Output:
<br>New dictionary :  {'emp01': 'Raj', 'emp02': 'Sheela', 'emp03': 'Joseph'}

In [50]:
Employee = {'emp 01' : 'Raj', 'emp 02' : 'Sheela', 'emp 0 3 ': 'Joseph'};

keys, values = list(Employee.keys()), list(Employee.values())

for i in range(len(keys)):
    keys[i] = ''.join(keys[i].split())

output = dict(zip(keys, values))

print(output)

{'emp01': 'Raj', 'emp02': 'Sheela', 'emp03': 'Joseph'}


### 16.  Write a program to display the subjects for which the scores are between 300 and 500 (inclusive) in the given dataframe

**Use the dataframe given below:**
    
<table>
 <tr>
 <th>Subject</th>
 <th>Score</th>
 </tr>
 <tr>
 <td>Maths</td>
 <td>345</td>
 </tr>
 <tr>
 <td>Physics</td>
 <td>432</td>
 </tr>
 <tr>
 <td>Chemistry</td>
 <td>456</td>
 </tr>
 <tr>
 <td>Biology</td>
 <td>234</td>
 </tr>
 <tr>
 <td>Geology</td>
 <td>254</td>
 </tr>
    
</table>

In [56]:
import pandas as pd

subjectScores = {
    'Subject': ['Maths', 'Physics', 'Chemistry', 'Biology', 'Geology'],
    'Score': [345, 432, 456, 234, 254]
}

df = pd.DataFrame(subjectScores)

output = df[(df.Score >= 300) & (df.Score <= 500)]
output

Subject  Score
0      Maths    345
1    Physics    432
2  Chemistry    456

### 17. Write a program to find numbers between 10000 to 20000 from a given array

**Use the list given below:**

Sales = [1432,143223,2043332,1642357,54327,754338,12459,75435,224454,1433,12447,25532,86674,74338,12678]

In [62]:
import numpy as np

Sales = np.array([1432,143223,2043332,1642357,54327,754338,12459,75435,224454,1433,12447,25532,86674,74338,12678])

output = Sales[(Sales >= 10000) & (Sales <= 20000)]
print(output)

[12459 12447 12678]


### 18. Write a program to sort the dataframe by Rank (in ascending order)

**Use the dataframe given below:**
    
<table>
 <tr>
 <th>Name</th>
 <th>Rank</th>
 </tr>
 <tr>
 <td>Joy</td>
 <td>115</td>
 </tr>
 <tr>
 <td>Mia</td>
 <td>451</td>
 </tr>
 <tr>
 <td>Karan</td>
 <td>341</td>
 </tr>
 <tr>
 <td>Tom</td>
 <td>84</td>
 </tr>
    
</table>

In [73]:
df = pd.DataFrame({
    'Name': ['Joy', 'Mia', 'Karan', 'Tom'],
    'Rank': [115, 451, 341, 84]
})

df.sort_values(by='Rank')


Name  Rank
3    Tom    84
0    Joy   115
2  Karan   341
1    Mia   451

### 19. Use the data given in the question 18, to do the following:
 Write a program to swap the 1st and 2nd row in a dataframe

In [74]:
print('before swapping\n', df)

temp = df.iloc[0]
df.iloc[0] = df.iloc[1]

df.iloc[1] = temp

print('After swapping\n', df)

before swapping
     Name  Rank
0    Joy   115
1    Mia   451
2  Karan   341
3    Tom    84
After swapping
     Name  Rank
0    Mia   451
1    Joy   115
2  Karan   341
3    Tom    84


### 20. Convert a 1D array to a 2D array containing 2 rows

**Use the array given below:**
    
dim_1 = ([331, 245, 246, 475, 348, 229])

In [80]:
dim_1 = np.array([331, 245, 246, 475, 348, 229])

dim_1.reshape(2, dim_1.shape[0] // 2)

array([[331, 245, 246],
       [475, 348, 229]])

### 21. Find the average cost of each variety of product available in the three different shops

**Use the data given below:**
    
[[10, 20, 30], [17, 14, 21], [25, 15, 12]],
  columns=['product_a', 'product_b', 'product_c'],
  index=['Shop1', 'Shop2', 'Shop3']

### 22. Write a program to delete items from series_a that are present in series_b and print the updated series_a

**Use the series given below:**
    
series_a = ([11, 12, 13, 14, 15])<br>
series_b= ([14, 15, 16, 17, 18])

In [92]:
series_a = [11, 12, 13, 14, 15]
series_b= [14, 15, 16, 17, 18]

series_a = [x for x in series_a if x not in series_b]
series_a

[11, 12, 13]

### 23. Get common elements from the two arrays

**Use the array given below:**<br>
      
      test_a = np.array([11,12,13,22,23,44,43,24,45,36])
      test_b = np.array([17,22,13,22,47,34,39,44,29,28])

In [87]:
test_a = np.array([11,12,13,22,23,44,43,24,45,36])
test_b = np.array([17,22,13,22,47,34,39,44,29,28])
np.intersect1d(test_a, test_b)



array([13, 22, 44])

### 24. Reverse each of the rows of the 2D array

**Use the array given below:**<br>

    num_array = np.arange(20).reshape(4,5)

In [82]:
num_array = np.arange(20).reshape(4,5)
num_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
print(num_array)

for i, row in enumerate(num_array):
    num_array[i] = row[::-1]

print(num_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
