In [1]:
import pandas as pd

In [2]:
data = {
    'name': ['Stan', 'Kyle', 'Eric', 'Kenny'],
    'age': [9, 9, 11, 12]
}
df = pd.DataFrame(data)

In [3]:
df.describe

<bound method NDFrame.describe of     name  age
0   Stan    9
1   Kyle    9
2   Eric   11
3  Kenny   12>

In [4]:
df.shape

(4, 2)

In [5]:
df.columns

Index(['name', 'age'], dtype='object')

In [6]:
import numpy as np

In [11]:
np.set_printoptions(legacy='1.13')
np.eye(8, 7, k=0)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
a[1]

array([4, 5, 6])

In [15]:
a[1, 1]

5

In [16]:
a[1][2]

6

In [17]:
a = np.zeros((3, 4))

In [18]:
for i in range(3):
    a[i] = np.array(list(map(int, input().split())))

In [19]:
a

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [20]:
x = map(int, input().split())

In [21]:
x

In [26]:
for i in x:
    print(i)

StopIteration: 

In [29]:
from math import pi

f'{pi:.6f}'

'3.141593'

In [30]:
import math

In [32]:
math.sqrt(4 + 1)

2.23606797749979

In [ ]:
(a + ib)(c + id)
ac + iad + ibc - bd

